version: '3'

volumes:
  data:

services:

  frontend:
    image: registry.bit-shifter.at/recipeapp.frontend
    restart: always
    container_name: recipe-frontend
    ports:
      - 5002:80
      - 5003:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend

  backend:
    image: registry.bit-shifter.at/recipeapp.backend
    restart: always
    container_name: recipe-backend
    ports:
      - 6060:80
      - 6067:433
    # environment:
    #   - ASPNETCORE_URLS=https://+:443;http://+:80
    #   - ASPNETCORE_Kestrel__Certificates__Default__Path=/etc/letsencrypt/live/pixeldance.at/fullchain.pem
    volumes:
      - /media/storage/recipe-app/logs:/app/logs
      - /media/storage/recipe-app/images:/app/wwwroot/images
      - /etc/letsencrypt:/etc/letsencrypt
    env_file:
      - app.env
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    container_name: recipe-postgres
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - db.env

  pgadmin:
    # image: dpage/pgadmin4
    image: biarms/pgadmin4
    restart: on-failure
    container_name: recipe-pg-admin
    ports:
      - 5005:5050
    volumes:
       - data:/var/lib/pgadmin
    env_file:
      - db.env
    depends_on:
      - database