version: '3'

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.Frontend
      args:
        - APP_NAME=recipe-app
    volumes:
      - ./Src/Webserver/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./Src/Webserver/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./storage/nginx/logs:/var/log/nginx

  backend:
    build:
      context: .
      dockerfile: Dockerfile.Backend
    volumes:
      - ./storage/logs:/app/logs
      - ./storage/images:/app/wwwroot/images